# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQx5eAWcJJsbPj99Q7jVdRc_-qoVlKjl
"""

print("sai")

print("i am going \ncollege for\tlearning nlp")

print("i am going college for\rlearning nlp")

import re

"""re.match()

"""

string="007 james bond wants to learn the python"
pattern=r'\d+'
matching=re.match(pattern,string)
matching.group()

import re
pattern=r'\d+'
string="007 james bond wants to learn the python"
matching=re.search(pattern,string)
matching.group()

import re
pattern=r'\d+'
string="007 james bond wants to learn the python"
matching=re.findall(pattern,string)
matching

import re
pattern=r'\d+'
string="007 james bond wants to learn the python"
matching=re.findall(pattern,string)
if matching:
    print(matching[0])
else:
    print("No matches found.")

import re
pattern=r'\d'
string="james bond 007 wants 008 to learn67 the python"
matching=re.sub(pattern,'@',string)
matching

# Test case
text = """
Hello world! Contact us at info@example.com or support123@company.org. Follow us on social media: #AI #MachineLearning.
Visit <a href="http://example.com">our website</a> for more details. This is a test with number 1234.
"""

pattern=r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
emails=re.findall(pattern,text)
emails

hash_tags=re.findall(r'@\w+',text)
hash_tags

